---
name: Net-Whois-Raw
version: 2.17
author:
  - |-
    Original author Ariel Brosh B<schop@cpan.org>, 
    Inspired by jwhois.pl available on the net.
  - |-
    Past maintainers Gabor Szabo B<gabor@perl.org.il>,
    Corris Randall B<corris@cpan.org>
  - 'Current Maintainer: Walery Studennikov B<despair@cpan.org>'
abstract: Get Whois information for domains
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Encode: 0
  Getopt::Long: 2
  HTTP::Headers: 0
  HTTP::Request: 0
  LWP::UserAgent: 0
  Test::More: 0
  URI::URL: 0
  perl: 5.008001
provides:
  Net::Whois::Raw:
    file: lib/Net/Whois/Raw.pm
    version: 2.17
  Net::Whois::Raw::Common:
    file: lib/Net/Whois/Raw/Common.pm
  Net::Whois::Raw::Data:
    file: lib/Net/Whois/Raw/Data.pm
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
